In [77]:
import numpy as np

In [78]:
# 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [79]:
arr=np.random.randint(1,101,size=(3,3))
print("Original Array:\n",arr)
trans=arr.T
print("\n After Interchanging row and column:\n",trans)

Original Array:
 [[46 95 24]
 [92 38 40]
 [75 71  4]]

 After Interchanging row and column:
 [[46 92 75]
 [95 38 71]
 [24 40  4]]


In [80]:
# 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [81]:
arr=np.random.randint(1,11,size=(1,10))
print("Array is: \n",arr)
arr25=arr.reshape(2,5)
print("\n Array of 2x5:\n",arr25)
arr52=arr.reshape(5,2)
print("\n Array of 5x2:\n",arr52)

Array is: 
 [[ 2  3  6  3  7 10  3  4  5  3]]

 Array of 2x5:
 [[ 2  3  6  3  7]
 [10  3  4  5  3]]

 Array of 5x2:
 [[ 2  3]
 [ 6  3]
 [ 7 10]
 [ 3  4]
 [ 5  3]]


In [82]:
# 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [83]:
arr=np.random.rand(4,4)
print("Array is: \n",arr)
arr_border=np.zeros((6,6))
arr_border[1:5,1:5]=arr
print("\n New Array is:\n",arr_border)

Array is: 
 [[0.87353824 0.95845448 0.99952286 0.76802231]
 [0.88753848 0.90885335 0.80431747 0.56573972]
 [0.41283942 0.0384597  0.54404361 0.43595494]
 [0.45182849 0.12371992 0.34660659 0.83179341]]

 New Array is:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.87353824 0.95845448 0.99952286 0.76802231 0.        ]
 [0.         0.88753848 0.90885335 0.80431747 0.56573972 0.        ]
 [0.         0.41283942 0.0384597  0.54404361 0.43595494 0.        ]
 [0.         0.45182849 0.12371992 0.34660659 0.83179341 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [84]:
# 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [85]:
arr=np.arange(10,61,5)
print("Array is:\n",arr)

Array is:
 [10 15 20 25 30 35 40 45 50 55 60]


In [86]:
# 5. Create a NumPy array of strings ['python','numpy','pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

In [87]:
arr=np.array(["python","numpy","pandas"])
print("Original Array:\n",arr)
arr2=np.char.upper(arr)
print("\nUppercase Array:\n",arr2)
arr2=np.char.lower(arr)
print("\nLowercase Array:\n",arr2)
arr2=np.char.title(arr)
print("\nTitle Array:\n",arr2)

Original Array:
 ['python' 'numpy' 'pandas']

Uppercase Array:
 ['PYTHON' 'NUMPY' 'PANDAS']

Lowercase Array:
 ['python' 'numpy' 'pandas']

Title Array:
 ['Python' 'Numpy' 'Pandas']


In [88]:
# 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [89]:
arr=np.array(["how","are","you","I","am","fine"])
print("Array of words:\n",arr)
sent=np.char.join(' ',arr.reshape(2,-1))
print("Array of sentence:\n",sent)

Array of words:
 ['how' 'are' 'you' 'I' 'am' 'fine']
Array of sentence:
 [['h o w' 'a r e' 'y o u']
 ['I' 'a m' 'f i n e']]


In [90]:
# 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [91]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2=np.array([[10,11,12],[13,14,15],[16,17,18]])
print("Array 1:\n",arr1)
print("Array 2:\n",arr2)
res=arr1+arr2
print("Addition of Array 1 and Array 2:\n",res)
res=arr2-arr1
print("Subtraction of Array 2 from Array 1 :\n",res)
res=arr1*arr2
print("Multiplication of Array 1 and Array 2:\n",res)
res=arr2/arr1
print("Division of Array 1 from Array 2:\n",res)

Array 1:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array 2:
 [[10 11 12]
 [13 14 15]
 [16 17 18]]
Addition of Array 1 and Array 2:
 [[11 13 15]
 [17 19 21]
 [23 25 27]]
Subtraction of Array 2 from Array 1 :
 [[9 9 9]
 [9 9 9]
 [9 9 9]]
Multiplication of Array 1 and Array 2:
 [[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]
Division of Array 1 from Array 2:
 [[10.          5.5         4.        ]
 [ 3.25        2.8         2.5       ]
 [ 2.28571429  2.125       2.        ]]


In [92]:
# 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [93]:
mat=np.eye(5)
print("Identity Matrix:\n",mat)
diag=np.diag(mat)
print("\nDiagonal Elements are:\n",diag)

Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements are:
 [1. 1. 1. 1. 1.]


In [94]:
# 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

In [95]:
arr=np.random.randint(1,1001,size=100)
print("Array is:\n",arr)
prime=[]
for i in arr:
  k=0
  z=int((i/2)+1)
  for j in range(2,z):
    if i%j==0:
      k+=1
  if k==0:
    prime.append(i)
print("Prime no Array is:\n",prime)

Array is:
 [505 587 372 195 233  33 674 919 227 872 746 160 665 199 559 345 195 361
 101 571 147 603 770 157 188 659  13 882 647 607 279 760 452 694 791 320
  61 810 511 618 919 404 163 422 686 862 725 999 586 915 133 280  10 271
 347 477 201 440 150 956 478 737 351 685 232 810 566 874 840 926  60 240
 675  93 727 617  11  95 123 314 313 956 587 377 620 492 257 678 776 882
 617  78 919 246 534 580 920 576 666  61]
Prime no Array is:
 [587, 233, 919, 227, 199, 101, 571, 157, 659, 13, 647, 607, 61, 919, 163, 271, 347, 727, 617, 11, 313, 587, 257, 617, 919, 61]


In [96]:
# 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [97]:
arr=np.random.randint(1,51,size=(4,7))
print("Daily Temperature:\n",arr)
week=np.mean(arr,axis=1)
print("Weekly Averages: \n", week)

Daily Temperature:
 [[31  5 24 39 39 34 14]
 [36 33 27 29 33 33 44]
 [10 39 22 35  7 11 21]
 [ 1 22 37 27 32 48 29]]
Weekly Averages: 
 [26.57142857 33.57142857 20.71428571 28.        ]
